services:
  app:
    labels:
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_app_main.middlewares=${COMPOSE_PROJECT_NAME}_app_main@docker"
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_app_main.basicauth.users=admin:$$2y$$05$$BjZarDhzxtq/n1OhmxEXlOY.lxvJo4vSAO1pdtL.6aFBd75mLpU/K"
