# This file is a template, and might need editing before it works on your project.
FROM node:21


RUN apt update
RUN apt install -y --no-install-recommends graphicsmagick && rm -rf /var/lib/apt/lists/*


WORKDIR /opt/app


COPY package.json /opt/app
RUN npm install

# COPY . /opt/app

EXPOSE 8000

# CMD ["/bin/sh", "-c", "npm start --release 2>&1 | tee -a logs/debug.log"]


CMD [ "npm", "start" ]